### ISSUE TITLE
Issue with limit setting in the latest master merge

### ISSUE THREAD

**Issue by SiminyA** [Seif-Abedsslem/ExpencesTracker#36]
at application.android.com.expencestracker.DBImp.UserTableImp.getLimit(UserTableImp.java:112)
        at application.android.com.expencestracker.MainActivity.notifyOnLimit(MainActivity.java:65)
        at application.android.com.expencestracker.MainActivity.onCreate(MainActivity.java:114)

Caused by: android.database.sqlite.SQLiteException: no such column: limit1 (code 1 SQLITE_ERROR): , while compiling: select userid _id ,limit1 from user_record where userid = 1

**Comment by SiminyA** [comment]
This issue is fixed
